[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://fitness-nutrition-backend.onrender.com" 